### Load packages

In [2]:
import pandas as pd
import os
import numpy as np

### Set file info for this run

In [3]:
# Project parameters

data_directory = r"..\data\merged_csvs"

algae_file = "algae_merged"
algae_path = os.path.join(data_directory, algae_file + ".csv")
print(algae_path)

..\data\merged_csvs\algae_merged.csv

### Load algae bloom data

In [4]:
# Load algae bloom data file

algae_raw_df = pd.read_csv(algae_path)

In [5]:
algae_raw_df.iloc[:5, :]
# vct_raw_df.iloc[:10, 10:25]
# vct_raw_df.iloc[:10, 10:25]

,vct_region,vct_report_date,vct_latitude,vct_longitude,vct_water_temp_trailing,vct_water_surface_trailing,vct_anabaena_trailing,vct_aphanizomenon_trailing,vct_microcystin_trailing,vct_oscillatoria_trailing,...,noaa_WDF5,noaa_TAVG,dec_total nitrogen,dec_total phosphorus,dec_dissolved phosphorus,dec_chlorophyll-a,dec_secchi depth,dec_temperature,vct_target_bloom,vct_target_bloom_intensity
0,Main Lake Central,2014-09-30,44.484736,-73.288936,66.608333,Calm,1.0,1.0,0.0,1.0,...,211.428571,15.228571,0.340,12.5,5.00,3.830,5.40,NaN,0,1a
1,Main Lake Central,2014-10-02,44.484736,-73.288936,66.169167,Calm,1.0,1.0,0.0,1.0,...,233.571429,15.328571,0.340,12.5,5.00,3.830,5.40,NaN,1,3
2,Main Lake Central,2015-06-14,44.484736,-73.288936,65.625000,Calm,1.0,0.0,0.0,0.0,...,254.285714,16.521429,0.400,69.6,13.00,2.300,5.00,12.0,0,1b
3,Main Lake Central,2015-06-15,44.484736,-73.288936,65.597222,Calm,1.0,0.0,0.0,0.0,...,250.000000,16.992857,0.400,69.6,13.00,2.300,5.00,12.0,0,1a
4,Main Lake Central,2015-06-16,44.484736,-73.288936,65.347222,Calm,1.0,0.0,0.0,0.0,...,252.142857,17.557143,0.405,39.7,9.65,1.815,4.05,14.2,0,1a

In [6]:
print(len(algae_raw_df.columns))
algae_raw_df.columns

35

Index(['vct_region', 'vct_report_date', 'vct_latitude', 'vct_longitude',
       'vct_water_temp_trailing', 'vct_water_surface_trailing',
       'vct_anabaena_trailing', 'vct_aphanizomenon_trailing',
       'vct_microcystin_trailing', 'vct_oscillatoria_trailing',
       'usgs_water_temp_max_trailing', 'usgs_water_temp_min_trailing',
       'usgs_water_temp_mean_trailing', 'usgs_conductivity_max_trailing',
       'usgs_conductivity_min_trailing', 'usgs_conductivity_mean_trailing',
       'noaa_PRCP', 'noaa_TMAX', 'noaa_TMIN', 'noaa_AWND', 'noaa_WSF2',
       'noaa_SNWD', 'noaa_WDF2', 'noaa_SNOW', 'noaa_WSF5', 'noaa_WDF5',
       'noaa_TAVG', 'dec_total nitrogen', 'dec_total phosphorus',
       'dec_dissolved phosphorus', 'dec_chlorophyll-a', 'dec_secchi depth',
       'dec_temperature', 'vct_target_bloom', 'vct_target_bloom_intensity'],
      dtype='object')

### Clean up and format data columns

In [7]:
# Convert columns to floats, integers, and dates as appropriate

algae_numcols_df = algae_raw_df.copy()

float_cols = ["vct_water_temp_trailing", "usgs_water_temp_max_trailing", "usgs_water_temp_min_trailing", "usgs_water_temp_mean_trailing", 
              "usgs_conductivity_max_trailing", "usgs_conductivity_min_trailing", "usgs_conductivity_mean_trailing",
              "noaa_PRCP", "noaa_TMIN", "noaa_TMAX", "noaa_AWND", "noaa_WDF2", "noaa_WSF2", "noaa_SNWD", "noaa_SNOW",
              "noaa_WSF5", "noaa_WDF5", "noaa_TAVG", "dec_total nitrogen", "dec_total phosphorus", "dec_dissolved phosphorus",
              "dec_chlorophyll-a", "dec_secchi depth", "dec_temperature"]
int_cols = ["vct_anabaena_trailing", "vct_aphanizomenon_trailing", "vct_microcystin_trailing", "vct_oscillatoria_trailing",
             "vct_target_bloom"]

algae_numcols_df[float_cols] = algae_numcols_df[float_cols].apply(pd.to_numeric, errors="coerce")

algae_numcols_df[int_cols] = (algae_numcols_df[int_cols].apply(pd.to_numeric, errors="coerce").astype("Int64"))

algae_numcols_df["vct_report_date"] = pd.to_datetime(algae_numcols_df["vct_report_date"])

algae_numcols_df.head()

,vct_region,vct_report_date,vct_latitude,vct_longitude,vct_water_temp_trailing,vct_water_surface_trailing,vct_anabaena_trailing,vct_aphanizomenon_trailing,vct_microcystin_trailing,vct_oscillatoria_trailing,...,noaa_WDF5,noaa_TAVG,dec_total nitrogen,dec_total phosphorus,dec_dissolved phosphorus,dec_chlorophyll-a,dec_secchi depth,dec_temperature,vct_target_bloom,vct_target_bloom_intensity
0,Main Lake Central,2014-09-30,44.484736,-73.288936,66.608333,Calm,1,1,0,1,...,211.428571,15.228571,0.340,12.5,5.00,3.830,5.40,NaN,0,1a
1,Main Lake Central,2014-10-02,44.484736,-73.288936,66.169167,Calm,1,1,0,1,...,233.571429,15.328571,0.340,12.5,5.00,3.830,5.40,NaN,1,3
2,Main Lake Central,2015-06-14,44.484736,-73.288936,65.625000,Calm,1,0,0,0,...,254.285714,16.521429,0.400,69.6,13.00,2.300,5.00,12.0,0,1b
3,Main Lake Central,2015-06-15,44.484736,-73.288936,65.597222,Calm,1,0,0,0,...,250.000000,16.992857,0.400,69.6,13.00,2.300,5.00,12.0,0,1a
4,Main Lake Central,2015-06-16,44.484736,-73.288936,65.347222,Calm,1,0,0,0,...,252.142857,17.557143,0.405,39.7,9.65,1.815,4.05,14.2,0,1a

### Prepare for modelling